export type Metal = "gold" | "silver" | "plated";
export type Occasion = "bridal" | "party" | "office" | "everyday";
export type Category = "necklace" | "earrings" | "ring" | "bangle" | "bracelet" | "anklet" | "tikka";
export type TryOnZone = "ear" | "hand" | "neck" | "forehead" | "wrist";

export type Product = {
  slug: string;
  name: string;
  urdu?: string;
  collection: string;
  category: Category;
  metal: Metal;
  karat?: "22k" | "18k" | "925";
  gemstone: string | null;
  occasion: Occasion[];
  price: number;
  compareAt?: number;
  weightG: number;
  makingPkr: number;
  hallmarked: boolean;
  antiTarnish: boolean;
  images: string[];
  overlay?: string;
  hoverImage?: string;
  description: string;
  details: string[];
  completeTheLook: string[];
  stackable?: boolean;
  tryOn?: TryOnZone;
  featured?: boolean;
  newest?: boolean;
  bestSeller?: boolean;
  defaultStock: number;
  sizeType?: "ring" | "bangle" | "none";
};

export const COLLECTIONS = [
  { slug: "bridal-couture", name: "Bridal Couture", blurb: "Trousseau pieces wrought for a lifetime." },
  { slug: "everyday-gold", name: "Everyday Gold", blurb: "Quiet 22k for the hours that are yours." },
  { slug: "office-edit", name: "The Office Edit", blurb: "Minimal lines that read as composure." },
  { slug: "party-lights", name: "Party Lights", blurb: "Gems that catch a room and keep it." },
  { slug: "silver-stones", name: "Silver & Stones", blurb: "Moonlight metal, made to live in." },
  { slug: "stack-layer", name: "Stack & Layer", blurb: "Build a language of rings and chains." },
] as const;

export const PRODUCTS: Product[] = [
  {
    slug: "noor-jahan",
    name: "Noor Jahan Bridal Set",
    urdu: "نور جہاں",
    collection: "bridal-couture",
    category: "necklace",
    metal: "gold",
    karat: "22k",
    gemstone: "polki",
    occasion: ["bridal"],
    price: 1850000,
    weightG: 86.4,
    makingPkr: 125000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/noor-jahan.jpg", "/products/noor-jahan-2.jpg"],
    hoverImage: "/products/noor-jahan-2.jpg",
    description:
      "A full bridal haar in 22k yellow gold, set with uncut polki and a hush of emerald silk-tone beads. Named for the empress who commissioned light itself. Each plaque is hand-cut in our Lahore atelier, then strung so the necklace sits close to the collarbone — a choker that becomes a story.",
    details: [
      "22k hallmarked gold, 86.4 g",
      "Uncut polki diamonds, emerald-tone beads",
      "Necklace, earrings and matching jhumka drops",
      "Adjustable silk-cord back",
      "Presented in a Sitara cedar box",
    ],
    completeTheLook: ["sitara-tikka", "pair-kangan", "lahore-jhumkas"],
    featured: true,
    newest: true,
    bestSeller: true,
    defaultStock: 2,
    sizeType: "none",
    tryOn: "neck",
  },
  {
    slug: "mughal-choker",
    name: "Mughal Empress Choker",
    collection: "bridal-couture",
    category: "necklace",
    metal: "gold",
    karat: "22k",
    gemstone: "kundan",
    occasion: ["bridal", "party"],
    price: 980000,
    weightG: 42.8,
    makingPkr: 78000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/mughal-choker.jpg"],
    description:
      "A closed kundan choker in the old Lahore manner — uncut stones bedded in gold foil, emerald beads at the drop. Meant to be worn with an open-necked peshwas or a modern silk shirt; it does not require a stage.",
    details: ["22k hallmarked gold, 42.8 g", "Kundan and polki setting", "Hidden box clasp"],
    completeTheLook: ["sitara-tikka", "sultan-ring", "lahore-jhumkas"],
    featured: true,
    defaultStock: 3,
    sizeType: "none",
    tryOn: "neck",
  },
  {
    slug: "sitara-tikka",
    name: "Sitara Maang Tikka",
    collection: "bridal-couture",
    category: "tikka",
    metal: "gold",
    karat: "22k",
    gemstone: "emerald",
    occasion: ["bridal"],
    price: 185000,
    weightG: 11.2,
    makingPkr: 18000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/sitara-tikka.jpg"],
    description:
      "A single star at the parting: a cabochon emerald held in 22k, with seed-pearl rain. Lightweight enough for a full baraat, grave enough for the photographs that last.",
    details: ["22k hallmarked gold, 11.2 g", "Emerald centre, freshwater pearls", "Hook-and-chain back"],
    completeTheLook: ["noor-jahan", "mughal-choker", "lahore-jhumkas"],
    newest: true,
    defaultStock: 5,
    sizeType: "none",
    tryOn: "forehead",
  },
  {
    slug: "lahore-jhumkas",
    name: "Lahore Jhumkas",
    urdu: "جھمکے",
    collection: "bridal-couture",
    category: "earrings",
    metal: "gold",
    karat: "22k",
    gemstone: "pearl",
    occasion: ["bridal", "party"],
    price: 125000,
    weightG: 16.8,
    makingPkr: 16000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/lahore-jhumkas.jpg"],
    overlay: "/overlays/jhumka.jpg",
    hoverImage: "/products/emerald-teardrop.jpg",
    description:
      "Bell jhumkas chased with floral jaali, finished with a single pearl. The silhouette is old Anarkali cinema; the weight is modern. They move when you do.",
    details: ["22k hallmarked gold, 16.8 g pair", "Pearl drops", "Secure hinged hoop"],
    completeTheLook: ["noor-jahan", "whisper-bangle", "thread-chain"],
    tryOn: "ear",
    featured: true,
    bestSeller: true,
    defaultStock: 4,
    sizeType: "none",
  },
  {
    slug: "pair-kangan",
    name: "Pair of Kangan",
    collection: "bridal-couture",
    category: "bangle",
    metal: "gold",
    karat: "22k",
    gemstone: null,
    occasion: ["bridal", "everyday"],
    price: 420000,
    weightG: 38.6,
    makingPkr: 24000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/pair-kangan.jpg"],
    description:
      "Two 22k kangan with Mughal floral engraving. A pair is the traditional gift; we sell them as they should be worn — together, with a faint chime.",
    details: ["22k hallmarked gold, 38.6 g pair", "Inner diameter 2.5\" (size 2.6 available)", "Hand-engraved"],
    completeTheLook: ["whisper-bangle", "dawn-stack", "noor-jahan"],
    stackable: true,
    defaultStock: 6,
    sizeType: "bangle",
    tryOn: "wrist",
  },
  {
    slug: "dawn-stack",
    name: "Dawn Stacking Ring",
    collection: "stack-layer",
    category: "ring",
    metal: "gold",
    karat: "22k",
    gemstone: "emerald",
    occasion: ["everyday", "office"],
    price: 42000,
    weightG: 2.1,
    makingPkr: 4500,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/dawn-stack.jpg"],
    overlay: "/overlays/ring.jpg",
    description:
      "A knife-edge 22k band with a single emerald baguette. Designed to be stacked in threes — buy one, or build the dawn.",
    details: ["22k hallmarked gold, 2.1 g", "Emerald baguette", "Comfort-fit band"],
    completeTheLook: ["whisper-bangle", "gold-hoops", "thread-chain"],
    stackable: true,
    tryOn: "hand",
    featured: true,
    newest: true,
    bestSeller: true,
    defaultStock: 12,
    sizeType: "ring",
  },
  {
    slug: "pearl-luna",
    name: "Pearl Luna Studs",
    collection: "office-edit",
    category: "earrings",
    metal: "gold",
    karat: "18k",
    gemstone: "pearl",
    occasion: ["office", "everyday"],
    price: 28500,
    weightG: 1.8,
    makingPkr: 3200,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/pearl-luna.jpg"],
    description:
      "7.5 mm cultured pearls on 18k posts. The daily earring that does not announce itself and is noticed anyway.",
    details: ["18k gold posts", "Cultured freshwater pearls", "Butterfly backs"],
    completeTheLook: ["thread-chain", "dawn-stack", "gold-hoops"],
    tryOn: "ear",
    bestSeller: true,
    defaultStock: 14,
    sizeType: "none",
  },
  {
    slug: "thread-chain",
    name: "Thread of Light Chain",
    collection: "everyday-gold",
    category: "necklace",
    metal: "gold",
    karat: "22k",
    gemstone: null,
    occasion: ["everyday", "office"],
    price: 95000,
    weightG: 6.4,
    makingPkr: 6500,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/thread-chain.jpg"],
    description:
      "A paperclip chain in 22k, 16 inches with a 2-inch extender. Fine enough for a collared shirt, sure enough to hold a future locket.",
    details: ["22k hallmarked gold, 6.4 g", "40 + 5 cm", "Lobster clasp"],
    completeTheLook: ["pearl-luna", "dawn-stack", "gold-hoops"],
    stackable: true,
    featured: true,
    defaultStock: 9,
    sizeType: "none",
    tryOn: "neck",
  },
  {
    slug: "whisper-bangle",
    name: "Whisper Bangle",
    collection: "everyday-gold",
    category: "bangle",
    metal: "gold",
    karat: "22k",
    gemstone: null,
    occasion: ["everyday", "office"],
    price: 78000,
    weightG: 8.2,
    makingPkr: 5200,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/whisper-bangle.jpg"],
    description:
      "An oval 22k bangle, high polish, no motif. It is the piece you forget you are wearing until someone asks.",
    details: ["22k hallmarked gold, 8.2 g", "Oval comfort shape", "Slip-on"],
    completeTheLook: ["dawn-stack", "pair-kangan", "pearl-luna"],
    stackable: true,
    tryOn: "wrist",
    newest: true,
    defaultStock: 8,
    sizeType: "bangle",
  },
  {
    slug: "gold-hoops",
    name: "Small Gold Hoops",
    collection: "office-edit",
    category: "earrings",
    metal: "gold",
    karat: "22k",
    gemstone: null,
    occasion: ["everyday", "office", "party"],
    price: 36000,
    weightG: 3.4,
    makingPkr: 3800,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/gold-hoops.jpg"],
    description:
      "20 mm 22k hoops with a click-hinge. The architecture of a good day.",
    details: ["22k hallmarked gold, 3.4 g pair", "20 mm diameter", "Hinged click"],
    completeTheLook: ["thread-chain", "dawn-stack", "pearl-luna"],
    tryOn: "ear",
    bestSeller: true,
    defaultStock: 11,
    sizeType: "none",
  },
  {
    slug: "emerald-teardrop",
    name: "Emerald Teardrop Earrings",
    collection: "party-lights",
    category: "earrings",
    metal: "gold",
    karat: "18k",
    gemstone: "emerald",
    occasion: ["party", "bridal"],
    price: 245000,
    weightG: 7.6,
    makingPkr: 22000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/emerald-teardrop.jpg"],
    hoverImage: "/products/lahore-jhumkas.jpg",
    description:
      "Zambian-colour emerald drops in 18k, each with a diamond-look halo. They read as heirloom under lamplight.",
    details: ["18k gold", "Faceted emerald drops", "Lever backs"],
    completeTheLook: ["sultan-ring", "constellation", "mughal-choker"],
    tryOn: "ear",
    featured: true,
    defaultStock: 3,
    sizeType: "none",
  },
  {
    slug: "constellation",
    name: "Constellation Bracelet",
    collection: "party-lights",
    category: "bracelet",
    metal: "plated",
    karat: "18k",
    gemstone: "cz",
    occasion: ["party", "office"],
    price: 16500,
    compareAt: 22000,
    weightG: 4.1,
    makingPkr: 0,
    hallmarked: false,
    antiTarnish: true,
    images: ["/products/constellation.jpg"],
    description:
      "A tennis line of brilliant-cut cubic zirconia in rhodium-finished white metal. Anti-tarnish plated. The night sky, made portable.",
    details: ["Rhodium-plated brass, CZ", "17 cm + extender", "Anti-tarnish coating"],
    completeTheLook: ["emerald-teardrop", "cz-solitaire", "rose-layered"],
    newest: true,
    defaultStock: 16,
    sizeType: "none",
    tryOn: "wrist",
  },
  {
    slug: "sultan-ring",
    name: "Sultan Cocktail Ring",
    collection: "party-lights",
    category: "ring",
    metal: "gold",
    karat: "22k",
    gemstone: "emerald",
    occasion: ["party", "bridal"],
    price: 320000,
    weightG: 9.8,
    makingPkr: 28000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/sultan-ring.jpg"],
    overlay: "/overlays/ring.jpg",
    description:
      "An oval emerald in a closed 22k gallery, diamond-look melee around the shoulder. A ring that ends a conversation politely.",
    details: ["22k hallmarked gold, 9.8 g", "Oval emerald", "Gallery setting"],
    completeTheLook: ["emerald-teardrop", "mughal-choker", "whisper-bangle"],
    tryOn: "hand",
    featured: true,
    defaultStock: 2,
    sizeType: "ring",
  },
  {
    slug: "ravi-chain",
    name: "Ravi Figaro Chain",
    collection: "everyday-gold",
    category: "necklace",
    metal: "gold",
    karat: "22k",
    gemstone: null,
    occasion: ["everyday", "party"],
    price: 210000,
    weightG: 14.2,
    makingPkr: 9000,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/ravi-chain.jpg"],
    description:
      "A denser 22k Figaro — the river chain. Wear it alone, or let it carry a future locket of someone you love.",
    details: ["22k hallmarked gold, 14.2 g", "45 cm", "Lobster clasp"],
    completeTheLook: ["gold-hoops", "whisper-bangle", "dawn-stack"],
    defaultStock: 5,
    sizeType: "none",
    tryOn: "neck",
  },
  {
    slug: "moonlight-choker",
    name: "Moonlight Silver Choker",
    collection: "silver-stones",
    category: "necklace",
    metal: "silver",
    karat: "925",
    gemstone: "moonstone",
    occasion: ["party", "everyday"],
    price: 18500,
    weightG: 28.0,
    makingPkr: 2400,
    hallmarked: true,
    antiTarnish: false,
    images: ["/products/moonlight-choker.jpg"],
    description:
      "Oxidized 925 silver with moonstone cabochons. A choker for nights that start too late and end too well.",
    details: ["925 sterling, oxidized", "Moonstone cabochons", "Hook clasp"],
    completeTheLook: ["payal-stars", "cz-solitaire", "rose-layered"],
    newest: true,
    defaultStock: 7,
    sizeType: "none",
    tryOn: "neck",
  },
  {
    slug: "payal-stars",
    name: "Payal of Stars",
    collection: "silver-stones",
    category: "anklet",
    metal: "silver",
    karat: "925",
    gemstone: null,
    occasion: ["everyday", "bridal"],
    price: 12800,
    weightG: 22.4,
    makingPkr: 1800,
    hallmarked: true,
    antiTarnish: false,
    images: ["/products/payal-stars.jpg"],
    description:
      "A pair of 925 payal with star charms and a quiet ghungroo. For the ankle that leads a room.",
    details: ["925 sterling, pair", "Adjustable 22–26 cm", "Star charms"],
    completeTheLook: ["moonlight-choker", "pearl-luna", "dawn-stack"],
    defaultStock: 10,
    sizeType: "none",
  },
  {
    slug: "cz-solitaire",
    name: "Light Solitaire",
    collection: "silver-stones",
    category: "ring",
    metal: "silver",
    karat: "925",
    gemstone: "cz",
    occasion: ["everyday", "office"],
    price: 8900,
    weightG: 3.2,
    makingPkr: 900,
    hallmarked: true,
    antiTarnish: true,
    images: ["/products/cz-solitaire.jpg"],
    overlay: "/overlays/ring.jpg",
    description:
      "A six-prong cubic zirconia on 925 silver, rhodium-finished. The promise ring that does not pretend to be a diamond — it pretends to be light.",
    details: ["925 silver, rhodium", "6 mm CZ", "Comfort band"],
    completeTheLook: ["constellation", "rose-layered", "pearl-luna"],
    stackable: true,
    tryOn: "hand",
    defaultStock: 18,
    sizeType: "ring",
  },
  {
    slug: "rose-layered",
    name: "Rose Layered Necklace",
    collection: "stack-layer",
    category: "necklace",
    metal: "plated",
    gemstone: null,
    occasion: ["everyday", "office", "party"],
    price: 6450,
    compareAt: 8900,
    weightG: 8.0,
    makingPkr: 0,
    hallmarked: false,
    antiTarnish: true,
    images: ["/products/rose-layered.jpg"],
    description:
      "Three lengths of rose-gold plating, a disc on the longest. Anti-tarnish. Built for layering with the Thread of Light if you graduate to gold.",
    details: ["Rose-gold plated brass", "Anti-tarnish", "Three-strand"],
    completeTheLook: ["gold-hoops", "cz-solitaire", "constellation"],
    stackable: true,
    newest: true,
    defaultStock: 20,
    sizeType: "none",
    tryOn: "neck",
  },
];

export const PRODUCT_BY_SLUG = Object.fromEntries(PRODUCTS.map((p) => [p.slug, p])) as Record<
  string,
  Product
>;

export function searchHaystack(p: Product): string {
  return [
    p.name,
    p.urdu ?? "",
    p.collection,
    p.category,
    p.metal,
    p.karat ?? "",
    p.gemstone ?? "",
    p.occasion.join(" "),
    p.description,
    p.details.join(" "),
  ].join(" ");
}

export const CATEGORY_LABEL: Record<Category, string> = {
  necklace: "Necklaces",
  earrings: "Earrings",
  ring: "Rings",
  bangle: "Bangles",
  bracelet: "Bracelets",
  anklet: "Anklets",
  tikka: "Tikka",
};

export const METAL_LABEL: Record<Metal, string> = {
  gold: "Gold",
  silver: "Silver",
  plated: "Plated",
};

export const OCCASION_LABEL: Record<Occasion, string> = {
  bridal: "Bridal",
  party: "Party",
  office: "Office",
  everyday: "Everyday",
};

export const GEMSTONES = Array.from(
  new Set(PRODUCTS.map((p) => p.gemstone).filter((g): g is string => Boolean(g))),
);

export const FREE_SHIPPING_OVER = 5000;
export const WHATSAPP_NUMBER = "923001112223";
export const STORE_NAME = "Sitara";
export const STORE_TAGLINE = "Starlight, wrought in gold.";
export const STORE_CITY = "Lahore";
