/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ArrivalsRouteImport } from './routes/arrivals'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as BestsellersRouteImport } from './routes/bestsellers'
import { Route as BridalRouteImport } from './routes/bridal'
import { Route as CareRouteImport } from './routes/care'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as MatchRouteImport } from './routes/match'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as StackRouteImport } from './routes/stack'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalsRoute = ArrivalsRouteImport.update({
  id: '/arrivals',
  path: '/arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const BestsellersRoute = BestsellersRouteImport.update({
  id: '/bestsellers',
  path: '/bestsellers',
  getParentRoute: () => rootRouteImport,
} as any)
const BridalRoute = BridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/arrivals': typeof ArrivalsRoute
  '/atelier': typeof AtelierRoute
  '/bestsellers': typeof BestsellersRoute
  '/bridal': typeof BridalRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/finder': typeof FinderRoute
  '/gifts': typeof GiftsRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/match': typeof MatchRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/stack': typeof StackRoute
  '/track': typeof TrackRoute
  '/try-on': typeof TryOnRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/arrivals': typeof ArrivalsRoute
  '/atelier': typeof AtelierRoute
  '/bestsellers': typeof BestsellersRoute
  '/bridal': typeof BridalRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/finder': typeof FinderRoute
  '/gifts': typeof GiftsRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/match': typeof MatchRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/returns': typeof ReturnsRoute
  '/size-guide': typeof SizeGuideRoute
  '/stack': typeof StackRoute
  '/track': typeof TrackRoute
  '/try-on': typeof TryOnRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/journal': typeof JournalIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/arrivals': typeof ArrivalsRoute
  '/atelier': typeof AtelierRoute
  '/bestsellers': typeof BestsellersRoute
  '/bridal': typeof BridalRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/craft': typeof CraftRoute
  '/finder': typeof FinderRoute
  '/gifts': typeof GiftsRoute
  '/journal': typeof JournalRouteWithChildren
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/match': typeof MatchRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/stack': typeof StackRoute
  '/track': typeof TrackRoute
  '/try-on': typeof TryOnRoute
  '/wishlist': typeof WishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/arrivals'
    | '/atelier'
    | '/bestsellers'
    | '/bridal'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/craft'
    | '/finder'
    | '/gifts'
    | '/journal'
    | '/login'
    | '/lookbook'
    | '/match'
    | '/privacy'
    | '/quiz'
    | '/returns'
    | '/shop'
    | '/size-guide'
    | '/stack'
    | '/track'
    | '/try-on'
    | '/wishlist'
    | '/category/$slug'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/shop/$slug'
    | '/journal/'
    | '/shop/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/arrivals'
    | '/atelier'
    | '/bestsellers'
    | '/bridal'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/craft'
    | '/finder'
    | '/gifts'
    | '/login'
    | '/lookbook'
    | '/match'
    | '/privacy'
    | '/quiz'
    | '/returns'
    | '/size-guide'
    | '/stack'
    | '/track'
    | '/try-on'
    | '/wishlist'
    | '/category/$slug'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/shop/$slug'
    | '/journal'
    | '/shop'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/arrivals'
    | '/atelier'
    | '/bestsellers'
    | '/bridal'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/craft'
    | '/finder'
    | '/gifts'
    | '/journal'
    | '/login'
    | '/lookbook'
    | '/match'
    | '/privacy'
    | '/quiz'
    | '/returns'
    | '/shop'
    | '/size-guide'
    | '/stack'
    | '/track'
    | '/try-on'
    | '/wishlist'
    | '/category/$slug'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/shop/$slug'
    | '/journal/'
    | '/shop/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ArrivalsRoute: typeof ArrivalsRoute
  AtelierRoute: typeof AtelierRoute
  BestsellersRoute: typeof BestsellersRoute
  BridalRoute: typeof BridalRoute
  CareRoute: typeof CareRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CraftRoute: typeof CraftRoute
  FinderRoute: typeof FinderRoute
  GiftsRoute: typeof GiftsRoute
  JournalRoute: typeof JournalRouteWithChildren
  LoginRoute: typeof LoginRoute
  LookbookRoute: typeof LookbookRoute
  MatchRoute: typeof MatchRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  ReturnsRoute: typeof ReturnsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SizeGuideRoute: typeof SizeGuideRoute
  StackRoute: typeof StackRoute
  TrackRoute: typeof TrackRoute
  TryOnRoute: typeof TryOnRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrivals': {
      id: '/arrivals'
      path: '/arrivals'
      fullPath: '/arrivals'
      preLoaderRoute: typeof ArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestsellers': {
      id: '/bestsellers'
      path: '/bestsellers'
      fullPath: '/bestsellers'
      preLoaderRoute: typeof BestsellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridal': {
      id: '/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof BridalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ArrivalsRoute: ArrivalsRoute,
  AtelierRoute: AtelierRoute,
  BestsellersRoute: BestsellersRoute,
  BridalRoute: BridalRoute,
  CareRoute: CareRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  CraftRoute: CraftRoute,
  FinderRoute: FinderRoute,
  GiftsRoute: GiftsRoute,
  JournalRoute: JournalRouteWithChildren,
  LoginRoute: LoginRoute,
  LookbookRoute: LookbookRoute,
  MatchRoute: MatchRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  ReturnsRoute: ReturnsRoute,
  ShopRoute: ShopRouteWithChildren,
  SizeGuideRoute: SizeGuideRoute,
  StackRoute: StackRoute,
  TrackRoute: TrackRoute,
  TryOnRoute: TryOnRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
